FROM mongo:latest

RUN apt-get update && apt-get install -y python3 \
    && rm -rf /var/lib/apt/lists/*

COPY dataset_reparacoes.json /docker-entrypoint-initdb.d/
COPY prepair.py /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/


RUN chmod +x /docker-entrypoint-initdb.d/import.sh
RUN chown -R mongodb:mongodb /docker-entrypoint-initdb.d/